############
## Project
############
name: test-scenekit

############
## Options
############
options:
  minimumXcodeGenVersion: 2.10
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "17.0"

#############
## Settings
#############
settings:
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  MARKETING_VERSION: "1.3.3"
  CURRENT_PROJECT_VERSION: "14"

############
## Targets
############
targets:
  # Name for our app target
  test-scenekit-app:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - path: test-scenekit
        group: app
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.yahya.test-scenekit"
      INFOPLIST_FILE: test-scenekit/Info.plist
      MARKETING_VERSION: 1.3.3
    entitlements:
      path: test-scenekit/test_scenekit.entitlements
